config/routes.rb
Rails.application.routes.draw do
  get 'products/show'
  root 'home#index'
  get 'static_pages/contact'
  get 'static_pages/about'

  devise_for :users, controllers: { registrations: 'registrations' }

  resources :products, only: [:index, :show]
  resources :categories, only: [:index, :show]
  resources :cart_items, only: [:update, :destroy]
  resources :orders, only: [:index, :new, :create, :show]

  namespace :admin do
    resources :orders do
      member do
        patch :update_status
      end
    end
    resources :products
    resources :categories
    resources :pages
    get 'dashboard', to: 'dashboard#index'
  end

  devise_scope :user do
    get 'sign_out', to: 'devise/sessions#destroy', as: :custom_destroy_user_session
  end

  resources :carts, only: [:show] do
    post 'add_product', on: :member
  end

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
end

app/models/product.rb
class Product < ApplicationRecord
  belongs_to :category
  validates :name, presence: true
  validates :price, presence: true, numericality: { greater_than: 0 }
  has_one_attached :image
  def image_url
    Rails.application.routes.url_helpers.rails_blob_url(image, only_path: true) if image.attached?
  end
  has_many :cart_items, dependent: :destroy
  has_many :order_items, dependent: :destroy
  paginates_per 20
end

app/controllers/admin/products_controller.rb
module Admin
  class ProductsController < ApplicationController
    before_action :authenticate_user!
    before_action :admin_only
    before_action :set_product, only: [:show, :edit, :update, :destroy]

    def index
      @products = Product.all
    end

    def show
    end

    def new
      @product = Product.new
    end

    def edit
    end

    def create
      @product = Product.new(product_params)

      if @product.save
        redirect_to admin_product_path(@product), notice: 'Product was successfully created.'
      else
        render :new
      end
    end

    def update
      if @product.update(product_params)
        redirect_to admin_product_path(@product), notice: 'Product was successfully updated.'
      else
        render :edit
      end
    end

    def destroy
      @product.destroy
      redirect_to admin_products_url, notice: 'Product was successfully destroyed.'
    end

    private

    def set_product
      @product = Product.find(params[:id])
    end

    def product_params
      params.require(:product).permit(:name, :description, :price, :image)
    end

    def admin_only
      unless current_user.admin?
        redirect_to root_path, alert: 'You are not authorized to access this section.'
      end
    end
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  skip_before_action :authenticate_user!, only: [:index, :show]

  def index
    @categories = Category.all
    @products = Product.all

    if params[:category].present?
      @products = @products.where(category_id: params[:category])
    end

    @products = @products.page(params[:page])
  end

  def show
    @product = Product.find(params[:id])
  end
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/admin/products/_form.html.erb
<%= form_with(model: [:admin, @product], local: true) do |form| %>
  <% if @product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
        <% @product.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description %>
  </div>

  <div class="field">
    <%= form.label :price %>
    <%= form.number_field :price %>
  </div>

  <div class="field">
    <%= form.label :image %>
    <%= form.file_field :image %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/admin/products/index.html.erb
<h1>Products</h1>

<%= link_to 'New Product', new_admin_product_path %>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th>Price</th>
      <th>Image</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @products.each do |product| %>
      <tr>
        <td><%= product.name %></td>
        <td><%= product.description %></td>
        <td><%= number_to_currency(product.price) %></td>
        <td>
          <% if product.image.attached? %>
            <%= image_tag product.image, size: "100x100" %>
          <% end %>
        </td>
        <td><%= link_to 'Show', admin_product_path(product) %></td>
        <td><%= link_to 'Edit', edit_admin_product_path(product) %></td>
        <td><%= link_to 'Destroy', admin_product_path(product), method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>