config/routes.rb
Rails.application.routes.draw do
  get 'products/show'
  root 'home#index'
  get 'static_pages/contact'
  get 'static_pages/about'

  devise_for :users, controllers: { registrations: 'registrations' }

  resources :products, only: [:index, :show]
  resources :categories, only: [:index, :show]
  resources :cart_items, only: [:update, :destroy]
  resources :orders, only: [:index, :new, :create, :show]

  namespace :admin do
    resources :orders do
      member do
        patch :update_status
      end
    end
    resources :products
    resources :categories
    resources :pages
    get 'dashboard', to: 'dashboard#index'
  end

  devise_scope :user do
    get 'sign_out', to: 'devise/sessions#destroy', as: :custom_destroy_user_session
  end

  resources :carts, only: [:show] do
    post 'add_product', on: :member
  end

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
end

app/models/address.rb
class Address < ApplicationRecord
  belongs_to :user
  belongs_to :province
  has_many :orders

  validates :street, :city, :province_id, :postal_code, presence: true
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart.rb
class Cart < ApplicationRecord
  belongs_to :user, optional: true
  has_many :cart_items, dependent: :destroy
  has_many :products, through: :cart_items

  def add_product(product_id)
    current_item = cart_items.find_by(product_id: product_id)
    if current_item
      current_item.quantity += 1
    else
      current_item = cart_items.build(product_id: product_id, quantity: 1)
    end
    current_item.save!
    current_item
  end

  def total_price
    cart_items.to_a.sum { |item| item.total_price }
  end
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
  belongs_to :cart
  belongs_to :product

  def total_price
    return 0 unless product && product.price && quantity
    product.price * quantity
  end
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :products
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :user
  has_many :order_items, dependent: :destroy
  belongs_to :address

  before_save :set_subtotal
  before_save :calculate_taxes

  def subtotal
    order_items.collect { |oi| oi.valid? ? (oi.quantity * oi.unit_price) : 0 }.sum
  end

  private

  def set_subtotal
    self[:subtotal] = subtotal
  end

  def calculate_taxes
    province = address.province
    self[:gst] = subtotal * (province.gst_rate / 100.0)
    self[:pst] = subtotal * (province.pst_rate / 100.0)
    self[:hst] = subtotal * (province.hst_rate / 100.0)
    self[:total_price] = subtotal + gst + pst + hst
  end
end

app/models/order_item.rb
class OrderItem < ApplicationRecord
  belongs_to :order
  belongs_to :product

  before_save :finalize

  def unit_price
    if persisted?
      self[:unit_price]
    else
      product.price
    end
  end

  def total_price
    unit_price * quantity
  end

  private

  def finalize
    self[:unit_price] = unit_price
    self[:total_price] = quantity * self[:unit_price]
  end
end

app/models/product.rb
class Product < ApplicationRecord
  belongs_to :category
  validates :name, presence: true
  validates :price, presence: true, numericality: { greater_than: 0 }
  has_one_attached :image
  def image_url
    Rails.application.routes.url_helpers.rails_blob_url(image, only_path: true) if image.attached?
  end
  has_many :cart_items, dependent: :destroy
  has_many :order_items, dependent: :destroy
  paginates_per 20
end

app/models/province.rb
class Province < ApplicationRecord
  has_many :taxes
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :user
  belongs_to :product
end

app/models/static_page.rb
class StaticPage < ApplicationRecord
end

app/models/tax.rb
class Tax < ApplicationRecord
  belongs_to :province
  belongs_to :tax_type
end

app/models/tax_type.rb
class TaxType < ApplicationRecord
  has_many :taxes
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :addresses, dependent: :destroy
  accepts_nested_attributes_for :addresses
  validates :email, presence: true, uniqueness: true
  has_many :orders, dependent: :destroy
  has_many :reviews, dependent: :destroy
  has_one :cart, dependent: :destroy
  attribute :admin, :boolean, default: false
  def admin?
    self.admin
  end
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  def show
    @cart = current_cart
  end

  def add_product
    product = Product.find(params[:product_id])
    @cart = current_cart
    @cart_item = @cart.add_product(product.id)

    if @cart_item.persisted?
      redirect_to @cart, notice: 'Product added to cart.'
    else
      redirect_to products_path, alert: 'Unable to add product to cart.'
    end
  end

  private

  def current_cart
    if user_signed_in?
      cart = current_user.cart || current_user.create_cart
    else
      cart = Cart.find_by(id: session[:cart_id])
      if cart.nil?
        cart = Cart.create
        session[:cart_id] = cart.id
      end
    end
    cart
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @categories = Category.all

    if params[:category_ids].present?
      @products = Product.joins(:category).where(categories: { id: params[:category_ids] }).page(params[:page]).per(10)
    elsif params[:search].present? && params[:search_category_id].present?
      @products = Product.joins(:category).where('categories.id = ? AND (LOWER(products.name) LIKE ? OR LOWER(products.description) LIKE ?)', params[:search_category_id], "%#{params[:search].downcase}%", "%#{params[:search].downcase}%").page(params[:page]).per(10)
    elsif params[:search].present?
      @products = Product.where('LOWER(name) LIKE ? OR LOWER(description) LIKE ?', "%#{params[:search].downcase}%", "%#{params[:search].downcase}%").page(params[:page]).per(10)
    else
      @products = Product.page(params[:page]).per(10)
    end
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_action :authenticate_user!

  def index
    @orders = current_user.orders
  end

  def show
    @order = current_user.orders.find(params[:id])
  end

  def new
    @order = current_user.orders.build
  end

  def create
    @order = current_user.orders.build(order_params)
    @order.add_cart_items(current_cart)
    @order.calculate_totals

    if @order.save
      session[:cart_id] = nil
      Stripe::Checkout::Session.create(
        payment_method_types: ['card'],
        line_items: @order.line_items_for_stripe,
        success_url: order_url(@order),
        cancel_url: cart_url(current_cart)
      )
      redirect_to @order, notice: 'Order was successfully created.'
    else
      render :new
    end
  end

  private

  def order_params
    params.require(:order).permit(:address_id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Anizkuro</title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbo-track': 'reload' %>
  <%= javascript_pack_tag 'application', 'data-turbo-track': 'reload' %>
</head>

<body>
  <header>
   <nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="<%= root_path %>">Anizkuro</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNav">
    <ul class="navbar-nav">
      <li class="nav-item">
        <%= link_to 'Home', root_path, class: 'nav-link' %>
      </li>
      <li class="nav-item">
        <%= link_to 'Contact', static_pages_contact_path, class: 'nav-link' %>
      </li>
      <li class="nav-item">
        <%= link_to 'About', static_pages_about_path, class: 'nav-link' %>
      </li>
      <li class="nav-item">
        <%= link_to 'Categories', categories_path, class: 'nav-link' %>
      </li>
      <% if user_signed_in? %>
      <li class="nav-item">
        <%= link_to 'Cart', cart_path(current_cart), class: 'nav-link' %>
      </li>
        <% if current_user.admin? %>
          <li class="nav-item">
            <%= link_to 'Admin', rails_admin_path, class: 'nav-link' %>
          </li>
        <% end %>
        <li class="nav-item">
          <%= link_to 'Logout', custom_destroy_user_session_path, method: :delete, data: { turbo: false }, class: 'nav-link' %>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to 'Login', new_user_session_path, class: 'nav-link' %>
        </li>
      <% end %>
    </ul>
  </div>
</nav>
  </header>
  <div class="container">
    <%= yield %>
  </div>
</body>
</html>